name: Tests on vim and neovim

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [false, true]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim or Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
      - name: Run Vader unit tests
        run: |
          if [ "${{ matrix.neovim }}" = "true" ]; then
            TESTVIM=nvim
          else
            TESTVIM=vim
          fi
          export TESTVIM
          ./test/run-tests.sh

  vint:
    name: Lint code with Vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install vint
        run: pip install --pre vim-vint
      - name: Lint
        run: vint --warning --enable-neovim ./after ./autoload ./compiler ./ftdetect ./ftplugin ./indent ./syntax
